### ISSUE TITLE
Going back from external website causes white screen

### ISSUE THREAD

**Issue by viktor-yakubiv** [oacore/dashboard#127]
Because we do not track pop state event for this moment we do not refresh state if the user left the website to external page and then come back using 'back' button. It causes white screen with no data.

**Comment by Joozty** [comment]
Would you mind to share with me a video? I tried firefox, chrome and is not possible to click on back button. Only safari allows it. I tried that and I didn't experience any white screen.

**Comment by viktor-yakubiv** [comment]
It was in Chrome. But the case is slightly weird. If you remove `target=_blank' router.push is triggered for an external URL so in this case Application should expect pop-state and it fails. I will record a video later.

**Comment by viktor-yakubiv** [comment]
Sorry, it's my fault. I cannot reproduce the issue.
