### ISSUE TITLE
CSV Export doesn't work

### ISSUE THREAD

**Issue by mcancellieri** [oacore/dashboard#132]
For big public release dates the csv export doesn't work, we need to find a way to make the exporting scalable.

**Comment by viktor-yakubiv** [comment]
@mcancellieri what is the status of this issue on the back-end side? Can we close this?

@Joozty could you also take a look at `download.js`, does it stream or cache response in memory? If it streams we can close it.

**Comment by mcancellieri** [comment]
Closing as it has been fixed by reducing sizes and improving the memory. Still not super-fast but ok for MVP
