### ISSUE TITLE
Improve login view

### ISSUE THREAD

**Issue by viktor-yakubiv** [oacore/dashboard#185]
1. Create a page `pages/login.jsx` where the login page is rendered as an iframe
2. Move `public/login.hml` to `public/secure/login.html` just in case if HTTP server set up to obfuscate `.html`
3. Display the application bar and navigation on login
4. If possible blur background under the iframe.

**Comment by Joozty** [comment]
> Display the application bar and navigation on the login

What's the point of having it there? Both will be empty only logo will be there.

> If possible blur background under the iframe.

Why?

We will need to get rid of redirection I guess. What happen in iframe when user log in? Like we discussed that iframe fires event to its parent but in the meantime, there should be something there. It's not clear for me.

**Comment by viktor-yakubiv** [comment]
Yes, because of the logo. We want the logo there but I do not know where to put it. This is an option.

Blur background is for hiding data. We can add a placeholder for it similar to what [Spectrum does](https://spectrum.chat/figma?tab=posts). Or we can have similar behaviour to [Privat24](https://next.privat24.ua) (click 'Entry' on the top right corner; it's a Ukrainian bank).

**Comment by Joozty** [comment]
@viktor-yakubiv Can it be closed or do you still want to improve the current state? 🙂
