### ISSUE TITLE
Add a loading bar for identifying network requests

### ISSUE THREAD

**Issue by viktor-yakubiv** [oacore/dashboard#188]
I propose to add a global loading state reporting to identify network requests running. I created a [pen](https://codepen.io/yakubiv/pen/VwLxyaj) how this could look like.

The proposed component can be embedded into the _Application_ to display the loading. The Application component could accept `loading` prop that is boolean. Also, the `Progress` component can be rendered contextually, e.g. n the top of the _Table_.

@Joozty how could this be integrated into the store?

**Comment by Joozty** [comment]
I can think of a very simple solution. Let me explain it. We will have loading property in the root store and this property will be simple increased/decreased by one. There is one caveat. The programmer is always responsible to clear loading state.

```jsx
class Root {
	isLoading = 0
	
	@action displayLoading() {
		this.isLoading += 1
	}

	@action hideLoading() {
		this.isLoading -= 1
	}
}
```

In the component, it would look like

```jsx
const Component = () => {
	useEffect(() => {
		try{
			store.setLoading()
			// api call here
		} finallly {
			store.hideLoading()
		}
	}, [])

	....
}

```

Loading component would look like:

```jsx
<LoadingBar loading={store.isLoading > 0} />
```

**Comment by viktor-yakubiv** [comment]
Above the AppBar I guess.

I would design the store chunk slightly differently:

```js
class Root {
  requestsInProgress = 0
  
  @computed
  get loading() {
    return this.requestsInProgress > 0
  }
}
```

About the component implementation I do not agree. I thing that all the requests should be executed from the Store and the counter should be increased in the store itself.

**Comment by Joozty** [comment]
I used actions because I read somewhere it's a good practice but to be honest I don't have any opinion about it. MobX allows [enforcing changing state only in actions](https://mobx.js.org/refguide/api.html#enforceactions). What do you think? 


Regarding the component implementation. I made it very general (for long-running tasks, not only API requests). If we want to have this only for API requests then I agree it should be only in the store.
