### ISSUE TITLE
Upgrade to new now.json config

### ISSUE THREAD

**Issue by Joozty** [oacore/dashboard#199]
`name` property in now.json has been deprecated. We should upgrade and do appropriate changes. 

See https://zeit.co/docs/configuration#project/name

**Comment by viktor-yakubiv** [comment]
I can fix this with #198. Is it only about name removing?

**Comment by viktor-yakubiv** [comment]
@Joozty sorry for messing the PR. I think that I edit `now.config.json` anyway there so I just put another change separately there.

**Comment by Joozty** [comment]
Yeah, go for it. I think it's only about removing `name` as you said. I didn't read it properly. I just saw deprecation warning hence I created task for it to not forgot about.
