### ISSUE TITLE
CSS modules process class names twice

### ISSUE THREAD

**Issue by viktor-yakubiv** [oacore/dashboard#22]
We need to load CSS files from @design/library globally, i.e. without CSS modules. Unfortunately, PostCSS doesn't support something like this:

```css
:global {
	import url('@oacore/design/lib/index.css')
}
```

Therefore we need to do it on WebPack level. But there was a problem when @oacore/design was symlinked because regular expression does not match.

Reported by @Joozty in #19

**Comment by viktor-yakubiv** [comment]
@Joozty would [this config](https://github.com/css-modules/webpack-demo/issues/23#issuecomment-255077927) solve the problem?

**Comment by Joozty** [comment]
I think we are fine with what we have now.

**Comment by viktor-yakubiv** [comment]
Please, reopen if this is not fixed.
