### ISSUE TITLE
Authorisation

### ISSUE THREAD

**Issue by viktor-yakubiv** [oacore/dashboard#31]
Develop logging in/our functionality for the Dashboard. It should be something really simple. We will more this functionality to global space but we should have it in the Dashboard for this moment.

For the authorisation we need the following:

- [x] Login page
- [x] Logout page

## Login page

It should be a simple web page, that contains a form with 2 fields: _email_ and _password_.

The form may contain hidden fields for security reasons. This will be considered layer.

The form should send a POST request to CORE API `/login`.

## Logout page

Logout page should automatically send GET request to CORE API `/logout`.

## Technical requirements

1. Login page must be written on pure HTML and placed to `/public` directory in the project, respectively `login.html`.
2. Logout page should be written on React (to be considered).
2. Pages should use custom build of [@oacore/design](GitHub.com/oacore/design) CSS with a specific CSS modules config (contact @viktor-yakubiv for more details).
3. Pages should have minimal or no JavaScript if possible.

## API endpoints

See more in the [Authorisation flow documentation](https://bitbucket.org/kmi-ou/core-api/src/master/docs/dashboard-authentication.md). Any technical questions to @valerapro.

**Comment by viktor-yakubiv** [comment]
@oacore/dashboard letting you know we are going to develop authorisation in such way. I wonder if you have any advice.

---

> The form may contain hidden fields for security reasons. This will be considered layer.

@mcancellieri do you have any concerns about  CSRF or XSS here?

**Comment by Joozty** [comment]
> Both pages must be written on pure HTML and placed to /public directory in the project, respectively login.html and logout.html

Isn't it contradictory to the second point? With this approach, we won't be able to load @oacore/design there unless we have "CDN".

**Comment by viktor-yakubiv** [comment]
This is security and we can do it with low effort.

I would maybe do logout on React. It would be easier and probably better. Updating

**Comment by viktor-yakubiv** [comment]
We have done enough for now.
