### ISSUE TITLE
Scrollbar hidden under app bar

### ISSUE THREAD

**Issue by Joozty** [oacore/dashboard#42]
I am not sure whether it's a bug or desired behavior. I incline more to 🐞. 

![Scroll](https://user-images.githubusercontent.com/12775440/71312910-6255a980-2431-11ea-9c07-2f07a3889dab.PNG)

**Comment by viktor-yakubiv** [comment]
It's definitely a bug but I do not know how to make it different. There are 2 ways:
1. make a container a level deeper scrollable instead current one
2. do some magic on html/body/#__next

I would start from the second one, it would be more transparent. If I fail I will consider other solutions.

It's not really urgent, we can live with it for some time.

**Comment by Joozty** [comment]
You will need to assign `overflow-y: auto;` to `html` element and remove `overflow-:auto;` from .container. Also, left sidebar will need to have `position: fixed;`
