### ISSUE TITLE
Application model design

### ISSUE THREAD

**Issue by viktor-yakubiv** [oacore/dashboard#63]
## Store

I imagine global store containing:
- `user` – user entity retrieved from `/user`
- `dataProviders` – current data-providers list retrieved from `/user/data-provider`, possible refined by user
- `dataProvider` – currently selected data provider; if there was no selected, the first one is picked automatically
- `activity` – currently selected user activity at the sidebar; name is considerable
- other stuff based on activity

### Global actions

1. Change/select data provider
2. Change/select activity

Both reflect URLs.

### Deposit dates

The activity requests data from `/data-provider/<id>/public-release-dates` and displays it.

#### Store appendix

- `works` ideally, `publicReleaseDates` considerable

#### Local actions

1. Load more/Next page to perform next request.

### Content

The activity requests data from `/data-provider/<id>/works` and displays it.

#### Store appendix

- `works` with items to render on the page

#### Local actions

1. Load more/Next page to perform next request.

**Comment by Joozty** [comment]
@viktor-yakubiv I think we somehow solved this already. Can we close it?

**Comment by viktor-yakubiv** [comment]
Yes, we can. Thank you!
