### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by Joozty** [oacore/dashboard#71]
I propose to have API like

```jsx
<Tooltip
 position="left|top|right|bottom"
 content="Tooltip content displayed on hover"
>
 {chidlren}
</Tooltip>
```

We need it for example in a table component when OAI is in short form. It would be great to show full OAI on hover in tooltip window.

Reference
https://getbootstrap.com/docs/4.0/components/tooltips/#examples

**Comment by viktor-yakubiv** [comment]
I checked [Reactstrap's Tooltips](https://reactstrap.github.io/components/tooltips/#app). It has really different API from proposed. I like yours much more.

If you find a way to use children for tooltip text it would be ideal. However, current proposal is good enough 👍

**Comment by Joozty** [comment]
Superseded by https://github.com/oacore/design/issues/290
